import './globals.css'
import Navbar from '../components/Navbar'

export const metadata = {
  title: "فروشگاه اینترنتی دیجیکالا",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa-IR" dir='rtl' className='font'>
      <body className='min-h-screen min-w-full'>
        <Navbar/>
        {children}
      </body>
    </html>
  )
}
